version: '3'

services:
  # nginx
  nginx-service:
    image: nginx:latest
    container_name: nginx-container-api
    ports:
      - "8082:80"
    volumes:
      - ./app-api:/app-api
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php7.4-service
      - mysql-service
    networks:
      - pdp-api

  # php
  php7.4-service:
    build:
      context: ./dockerfiles/php/
      dockerfile: Dockerfile
    container_name: php-container-api
    ports:
      - "9002:9000"
    volumes:
      - ./app-api:/app-api
    depends_on:
      - mysql-service
    networks:
      - pdp-api

  # mysql
  mysql-service:
    image: mysql:5.7
    container_name: mysql-container-api
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_USER: pdp_user
      MYSQL_DATABASE: pdp_database
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - pdp-api

networks:
  pdp-api:
    driver: bridge