version: '3'

services:
  # nginx
  nginx-service:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./app-api:/app-api
      - ./dockerfiles/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php7.4-service
    networks:
      - pdp-api

  # php
  php7.4-service:
    build:
      context: .
      dockerfile: ./dockerfiles/php/Dockerfile
    container_name: php-container
    ports:
      - "9000:9000"
    volumes:
      - ./app-api:/app-api
    networks:
      - pdp-api

networks:
  pdp-api:
